uint8 HW_RESET_IMMEDIATELY=0x00
uint8 SW_RESET_CONTROLLED=0x01
uint8 SW_RESET_CONTROLLED_GNSS=0x02
uint8 HW_RESET_AFTER_SHUTDOWN=0x04
uint8 GNSS_STOP_CONTROLLED=0x08
uint8 GNSS_START_CONTROLLED=0x09
uint8 reset_type
---