# UBX-CFG Parameters Configuration File
# TOML version of the configuration (converted from JSON)

# Basic version information
version = "1.0.0"
device_types = ["ZED-F9P", "ZED-F9R"]

# Firmware version information
[firmware_versions]

# ZED-F9P firmware versions
[[firmware_versions.ZED-F9P]]
version = "HPG 1.30"
description = "Initial production release"
release_date = "2022-01-15"

[[firmware_versions.ZED-F9P]]
version = "HPG 1.32"
description = "Latest production release with enhanced RTK performance"
release_date = "2024-01-14"

# ZED-F9R firmware versions
[[firmware_versions.ZED-F9R]]
version = "HPS 1.20"
description = "Initial production release"
release_date = "2022-03-10"

[[firmware_versions.ZED-F9R]]
version = "HPS 1.30"
description = "Latest production release with enhanced dead reckoning"
release_date = "2024-01-14"

# Parameters configuration

# Parameter: CFG_INFMSG_UBX_USB
[[parameters]]
name = "CFG_INFMSG_UBX_USB"
key_id = "0x20920004"
type = "X1"
scale = 1.0
unit = "NA"
applicable_devices = ["ZED-F9P", "ZED-F9R"]
description = "Information message configuration for UBX protocol on USB"
default_value = "0x00"
group = "INFMSG"

[parameters.possible_values]
INFMSG_ERROR = "0x01"
INFMSG_WARNING = "0x02"
INFMSG_NOTICE = "0x04"
INFMSG_TEST = "0x08"
INFMSG_DEBUG = "0x10"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

[parameters.firmware_support.ZED-F9R]
since = "HPS 1.20"

# Parameter: CFG_UART1INPROT_UBX
[[parameters]]
name = "CFG_UART1INPROT_UBX"
key_id = "0x10730001"
type = "L"
scale = 1.0
unit = "NA"
applicable_devices = ["ZED-F9P", "ZED-F9R"]
description = "Flag to indicate if UBX protocol is used for input on UART1"
default_value = "0x01"
group = "UART"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

[parameters.firmware_support.ZED-F9R]
since = "HPS 1.20"

# Parameter: CFG_UART1OUTPROT_UBX
[[parameters]]
name = "CFG_UART1OUTPROT_UBX"
key_id = "0x10740001"
type = "L"
scale = 1.0
unit = "NA"
applicable_devices = ["ZED-F9P", "ZED-F9R"]
description = "Flag to indicate if UBX protocol is used for output on UART1"
default_value = "0x01"
group = "UART"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

[parameters.firmware_support.ZED-F9R]
since = "HPS 1.20"

# Parameter: CFG_UART2_BAUDRATE
[[parameters]]
name = "CFG_UART2_BAUDRATE"
key_id = "0x40530001"
type = "U4"
scale = 1.0
unit = "NA"
applicable_devices = ["ZED-F9P", "ZED-F9R"]
description = "UART2 baud rate in bits per second"
default_value = "0x00038400"
min_value = "0x00004B00"
max_value = "0x00E1000"
group = "UART"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

[parameters.firmware_support.ZED-F9R]
since = "HPS 1.20"

# Parameter: CFG_TMODE_MODE
[[parameters]]
name = "CFG_TMODE_MODE"
key_id = "0x20030001"
type = "E1"
scale = 1.0
unit = "NA"
applicable_devices = ["ZED-F9P"]
description = "Time mode configuration mode"
default_value = "0x00"
group = "TMODE"

[parameters.possible_values]
DISABLED = "0x00"
SURVEY_IN = "0x01"
FIXED = "0x02"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

# Parameter: CFG_RATE_MEAS
[[parameters]]
name = "CFG_RATE_MEAS"
key_id = "0x30210001"
type = "U2"
scale = 0.001
unit = "S"
applicable_devices = ["ZED-F9P", "ZED-F9R"]
description = "Measurement rate in seconds"
default_value = "0x00C8"
min_value = "0x0001"
max_value = "0xFFFF"
group = "RATE"
notes = "The measurement rate has a resolution of 0.001 seconds (1ms)"

[parameters.firmware_support.ZED-F9P]
since = "HPG 1.30"

[[parameters.firmware_support.ZED-F9P.behavior_changes]]
version = "HPG 1.32"
description = "Improved handling of very low measurement rates"

[parameters.firmware_support.ZED-F9R]
since = "HPS 1.20"
