// Copyright 2025 GreenForge Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @file ubx_cfg_item.cpp
 * @brief Implementation of UBX configuration item functions
 */

#include "ublox_dgnss_node/ubx/ubx_cfg_item.hpp"

namespace ubx::cfg
{

size_t storage_size_bytes(u8_t storage_size_id)
{
  size_t size = 0;
  switch (storage_size_id) {
    case 0x01: size = 1; break;     /// one bit but uses one byte
    case 0x02: size = 1; break;
    case 0x03: size = 2; break;
    case 0x04: size = 4; break;
    case 0x05: size = 8; break;
    default:
      size = 0;
  }
  return size;
}

bool operator<(const ubx_key_id_t & fk1, const ubx_key_id_t & fk2)
{
  return fk1.all < fk2.all;
}

bool operator==(const ubx_key_id_t & fk1, uint32_t value)
{
  return fk1.all == value;
}

bool operator==(uint32_t value, const ubx_key_id_t & fk1)
{
  return fk1.all == value;
}

// Definition of the global map of UBX key IDs to UBX configuration items
std::map<ubx_key_id_t, ubx_cfg_item_t> ubxKeyCfgItemMap = {
  {CFG_INFMSG_UBX_USB.ubx_key_id, CFG_INFMSG_UBX_USB},
  {CFG_INFMSG_NMEA_USB.ubx_key_id, CFG_INFMSG_NMEA_USB},
  {CFG_UART1INPROT_UBX.ubx_key_id, CFG_UART1INPROT_UBX},
  {CFG_UART1INPROT_NMEA.ubx_key_id, CFG_UART1INPROT_NMEA},
  {CFG_UART1INPROT_RTCM3X.ubx_key_id, CFG_UART1INPROT_RTCM3X},
  {CFG_UART1INPROT_SPARTN.ubx_key_id, CFG_UART1INPROT_SPARTN},
  {CFG_UART1OUTPROT_UBX.ubx_key_id, CFG_UART1OUTPROT_UBX},
  {CFG_UART1OUTPROT_NMEA.ubx_key_id, CFG_UART1OUTPROT_NMEA},
  {CFG_UART1OUTPROT_RTCM3X.ubx_key_id, CFG_UART1OUTPROT_RTCM3X},
  {CFG_UART2_BAUDRATE.ubx_key_id, CFG_UART2_BAUDRATE},
  {CFG_UART2INPROT_UBX.ubx_key_id, CFG_UART2INPROT_UBX},
  {CFG_UART2INPROT_NMEA.ubx_key_id, CFG_UART2INPROT_NMEA},
  {CFG_UART2INPROT_RTCM3X.ubx_key_id, CFG_UART2INPROT_RTCM3X},
  {CFG_UART2INPROT_SPARTN.ubx_key_id, CFG_UART2INPROT_SPARTN},
  {CFG_UART2OUTPROT_UBX.ubx_key_id, CFG_UART2OUTPROT_UBX},
  {CFG_UART2OUTPROT_NMEA.ubx_key_id, CFG_UART2OUTPROT_NMEA},
  {CFG_UART2OUTPROT_RTCM3X.ubx_key_id, CFG_UART2OUTPROT_RTCM3X},
  {CFG_USBINPROT_UBX.ubx_key_id, CFG_USBINPROT_UBX},
  {CFG_USBINPROT_NMEA.ubx_key_id, CFG_USBINPROT_NMEA},
  {CFG_USBINPROT_RTCM3X.ubx_key_id, CFG_USBINPROT_RTCM3X},
  {CFG_USBOUTPROT_UBX.ubx_key_id, CFG_USBOUTPROT_UBX},
  {CFG_USBOUTPROT_NMEA.ubx_key_id, CFG_USBOUTPROT_NMEA},
  {CFG_USBOUTPROT_RTCM3X.ubx_key_id, CFG_USBOUTPROT_RTCM3X},
  {CFG_SPARTN_USE_SOURCE.ubx_key_id, CFG_SPARTN_USE_SOURCE},
  {CFG_TMODE_MODE.ubx_key_id, CFG_TMODE_MODE},
  {CFG_TMODE_POS_TYPE.ubx_key_id, CFG_TMODE_POS_TYPE},
  {CFG_TMODE_ECEF_X.ubx_key_id, CFG_TMODE_ECEF_X},
  {CFG_TMODE_ECEF_Y.ubx_key_id, CFG_TMODE_ECEF_Y},
  {CFG_TMODE_ECEF_Z.ubx_key_id, CFG_TMODE_ECEF_Z},
  {CFG_TMODE_ECEF_X_HP.ubx_key_id, CFG_TMODE_ECEF_X_HP},
  {CFG_TMODE_ECEF_Y_HP.ubx_key_id, CFG_TMODE_ECEF_Y_HP},
  {CFG_TMODE_ECEF_Z_HP.ubx_key_id, CFG_TMODE_ECEF_Z_HP},
  {CFG_TMODE_LAT.ubx_key_id, CFG_TMODE_LAT},
  {CFG_TMODE_LON.ubx_key_id, CFG_TMODE_LON},
  {CFG_TMODE_HEIGHT.ubx_key_id, CFG_TMODE_HEIGHT},
  {CFG_TMODE_LAT_HP.ubx_key_id, CFG_TMODE_LAT_HP},
  {CFG_TMODE_LON_HP.ubx_key_id, CFG_TMODE_LON_HP},
  {CFG_TMODE_HEIGHT_HP.ubx_key_id, CFG_TMODE_HEIGHT_HP},
  {CFG_TMODE_FIXED_POS_ACC.ubx_key_id, CFG_TMODE_FIXED_POS_ACC},
  {CFG_TMODE_SVIN_MIN_DUR.ubx_key_id, CFG_TMODE_SVIN_MIN_DUR},
  {CFG_TMODE_SVIN_ACC_LIMIT.ubx_key_id, CFG_TMODE_SVIN_ACC_LIMIT},
  {CFG_NAVHPG_DGNSSMODE.ubx_key_id, CFG_NAVHPG_DGNSSMODE},
  {CFG_NAVSPG_FIXMODE.ubx_key_id, CFG_NAVSPG_FIXMODE},
  {CFG_NAVSPG_INIFIX3D.ubx_key_id, CFG_NAVSPG_INIFIX3D},
  {CFG_NAVSPG_UTCSTANDARD.ubx_key_id, CFG_NAVSPG_UTCSTANDARD},
  {CFG_NAVSPG_DYNMODEL.ubx_key_id, CFG_NAVSPG_DYNMODEL},

  {CFG_SEC_SPOOFDET_SIM_SIG_DIS.ubx_key_id, CFG_SEC_SPOOFDET_SIM_SIG_DIS},
  {CFG_SEC_JAMDET_SENSITIVITY_HI.ubx_key_id, CFG_SEC_JAMDET_SENSITIVITY_HI},

  {CFG_SIGNAL_GPS_ENA.ubx_key_id, CFG_SIGNAL_GPS_ENA},
  {CFG_SIGNAL_GPS_L1CA_ENA.ubx_key_id, CFG_SIGNAL_GPS_L1CA_ENA},
  {CFG_SIGNAL_GPS_L2C_ENA.ubx_key_id, CFG_SIGNAL_GPS_L2C_ENA},
  {CFG_SIGNAL_SBAS_ENA.ubx_key_id, CFG_SIGNAL_SBAS_ENA},
  {CFG_SIGNAL_SBAS_L1CA_ENA.ubx_key_id, CFG_SIGNAL_SBAS_L1CA_ENA},
  {CFG_SIGNAL_GAL_ENA.ubx_key_id, CFG_SIGNAL_GAL_ENA},
  {CFG_SIGNAL_GAL_E1_ENA.ubx_key_id, CFG_SIGNAL_GAL_E1_ENA},
  {CFG_SIGNAL_GAL_E5B_ENA.ubx_key_id, CFG_SIGNAL_GAL_E5B_ENA},
  {CFG_SIGNAL_BDS_ENA.ubx_key_id, CFG_SIGNAL_BDS_ENA},
  {CFG_SIGNAL_BDS_B1_ENA.ubx_key_id, CFG_SIGNAL_BDS_B1_ENA},
  {CFG_SIGNAL_BDS_B2_ENA.ubx_key_id, CFG_SIGNAL_BDS_B2_ENA},
  {CFG_SIGNAL_QZSS_ENA.ubx_key_id, CFG_SIGNAL_QZSS_ENA},
  {CFG_SIGNAL_QZSS_L1CA_ENA.ubx_key_id, CFG_SIGNAL_QZSS_L1CA_ENA},
  {CFG_SIGNAL_QZSS_L1S_ENA.ubx_key_id, CFG_SIGNAL_QZSS_L1S_ENA},
  {CFG_SIGNAL_QZSS_L2C_ENA.ubx_key_id, CFG_SIGNAL_QZSS_L2C_ENA},
  {CFG_SIGNAL_GLO_ENA.ubx_key_id, CFG_SIGNAL_GLO_ENA},
  {CFG_SIGNAL_GLO_L1_ENA.ubx_key_id, CFG_SIGNAL_GLO_L1_ENA},
  {CFG_SIGNAL_GLO_L2_ENA.ubx_key_id, CFG_SIGNAL_GLO_L2_ENA},

  {CFG_ODO_USE_ODO.ubx_key_id, CFG_ODO_USE_ODO},
  {CFG_ODO_USE_COG.ubx_key_id, CFG_ODO_USE_COG},
  {CFG_ODO_OUTLPVEL.ubx_key_id, CFG_ODO_OUTLPVEL},
  {CFG_ODO_OUTLPCOG.ubx_key_id, CFG_ODO_OUTLPCOG},
  {CFG_ODO_PROFILE.ubx_key_id, CFG_ODO_PROFILE},
  {CFG_ODO_COGMAXSPEED.ubx_key_id, CFG_ODO_COGMAXSPEED},
  {CFG_ODO_COGMAXPOSACC.ubx_key_id, CFG_ODO_COGMAXPOSACC},
  {CFG_ODO_VELLPGAIN.ubx_key_id, CFG_ODO_VELLPGAIN},
  {CFG_ODO_COGLPGAIN.ubx_key_id, CFG_ODO_COGLPGAIN},

  {CFG_RATE_MEAS.ubx_key_id, CFG_RATE_MEAS},
  {CFG_RATE_NAV.ubx_key_id, CFG_RATE_NAV},
  {CFG_RATE_TIMEREF.ubx_key_id, CFG_RATE_TIMEREF},

  {CFG_SFIMU_AUTO_MNTALG_ENA.ubx_key_id, CFG_SFIMU_AUTO_MNTALG_ENA},
  {CFG_SFIMU_IMU_MNTALG_YAW.ubx_key_id, CFG_SFIMU_IMU_MNTALG_YAW},
  {CFG_SFIMU_IMU_MNTALG_PITCH.ubx_key_id, CFG_SFIMU_IMU_MNTALG_PITCH},
  {CFG_SFIMU_IMU_MNTALG_ROLL.ubx_key_id, CFG_SFIMU_IMU_MNTALG_ROLL},

  {CFG_SFODO_COMBINE_TICKS.ubx_key_id, CFG_SFODO_COMBINE_TICKS},
  {CFG_SFODO_COUNT_MAX.ubx_key_id, CFG_SFODO_COUNT_MAX},
  {CFG_SFODO_DIS_AUTOCOUNTMAX.ubx_key_id, CFG_SFODO_DIS_AUTOCOUNTMAX},
  {CFG_SFODO_DIS_AUTODIRPINPOL.ubx_key_id, CFG_SFODO_DIS_AUTODIRPINPOL},
  {CFG_SFODO_FACTOR.ubx_key_id, CFG_SFODO_FACTOR},
  {CFG_SFODO_LATENCY.ubx_key_id, CFG_SFODO_LATENCY},
  {CFG_SFODO_QUANT_ERROR.ubx_key_id, CFG_SFODO_QUANT_ERROR},

  {CFG_MSGOUT_UBX_NAV_STATUS_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_STATUS_USB},
  {CFG_MSGOUT_UBX_NAV_SVIN_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_SVIN_USB},
  {CFG_MSGOUT_UBX_NAV_CLOCK_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_CLOCK_USB},
  {CFG_MSGOUT_UBX_NAV_COV_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_COV_USB},
  {CFG_MSGOUT_UBX_NAV_DOP_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_DOP_USB},
  {CFG_MSGOUT_UBX_NAV_EOE_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_EOE_USB},
  {CFG_MSGOUT_UBX_NAV_POSECEF_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_POSECEF_USB},
  {CFG_MSGOUT_UBX_NAV_HPPOSECEF_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_HPPOSECEF_USB},
  {CFG_MSGOUT_UBX_NAV_POSLLH_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_POSLLH_USB},
  {CFG_MSGOUT_UBX_NAV_HPPOSLLH_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_HPPOSLLH_USB},
  {CFG_MSGOUT_UBX_NAV_ODO_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_ODO_USB},
  {CFG_MSGOUT_UBX_NAV_ORB_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_ORB_USB},
  {CFG_MSGOUT_UBX_NAV_SAT_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_SAT_USB},
  {CFG_MSGOUT_UBX_NAV_SIG_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_SIG_USB},
  {CFG_MSGOUT_UBX_NAV_PVT_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_PVT_USB},
  {CFG_MSGOUT_UBX_NAV_RELPOSNED_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_RELPOSNED_USB},
  {CFG_MSGOUT_UBX_NAV_TIMEUTC_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_TIMEUTC_USB},
  {CFG_MSGOUT_UBX_NAV_VELECEF_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_VELECEF_USB},
  {CFG_MSGOUT_UBX_NAV_VELNED_USB.ubx_key_id, CFG_MSGOUT_UBX_NAV_VELNED_USB},
  {CFG_MSGOUT_UBX_RXM_COR_USB.ubx_key_id, CFG_MSGOUT_UBX_RXM_COR_USB},
  {CFG_MSGOUT_UBX_RXM_RTCM_USB.ubx_key_id, CFG_MSGOUT_UBX_RXM_RTCM_USB},
  {CFG_MSGOUT_UBX_RXM_MEASX_USB.ubx_key_id, CFG_MSGOUT_UBX_RXM_MEASX_USB},
  {CFG_MSGOUT_UBX_RXM_RAWX_USB.ubx_key_id, CFG_MSGOUT_UBX_RXM_RAWX_USB},
  {CFG_MSGOUT_UBX_MON_COMMS_USB.ubx_key_id, CFG_MSGOUT_UBX_MON_COMMS_USB},
  {CFG_MSGOUT_UBX_RXM_SPARTN_USB.ubx_key_id, CFG_MSGOUT_UBX_RXM_SPARTN_USB},
  {CFG_MSGOUT_UBX_ESF_MEAS_USB.ubx_key_id, CFG_MSGOUT_UBX_ESF_MEAS_USB},
  {CFG_MSGOUT_UBX_ESF_STATUS_USB.ubx_key_id, CFG_MSGOUT_UBX_ESF_STATUS_USB},
  {CFG_MSGOUT_UBX_SEC_SIG_USB.ubx_key_id, CFG_MSGOUT_UBX_SEC_SIG_USB},
  {CFG_MSGOUT_UBX_SEC_SIGLOG_USB.ubx_key_id, CFG_MSGOUT_UBX_SEC_SIGLOG_USB},

  // Support both USB type and UART2 type messages simultaneously
  {CFG_MSGOUT_RTCM_3X_TYPE1005_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1005_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1077_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1077_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1087_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1087_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1097_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1097_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1127_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1127_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1230_USB.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1230_USB},
  {CFG_MSGOUT_RTCM_3X_TYPE1074_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1074_UART2},
  {CFG_MSGOUT_RTCM_3X_TYPE1084_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1084_UART2},
  {CFG_MSGOUT_RTCM_3X_TYPE1094_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1094_UART2},
  {CFG_MSGOUT_RTCM_3X_TYPE1124_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1124_UART2},
  {CFG_MSGOUT_RTCM_3X_TYPE1230_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE1230_UART2},
  {CFG_MSGOUT_RTCM_3X_TYPE4072_0_UART2.ubx_key_id, CFG_MSGOUT_RTCM_3X_TYPE4072_0_UART2}

  // removed in latest F9P 1.5 firmware
  // {CFG_ITFM_BBTHRESHOLD.ubx_key_id, CFG_ITFM_BBTHRESHOLD},
  // {CFG_ITFM_CWTHRESHOLD.ubx_key_id, CFG_ITFM_CWTHRESHOLD},
  // {CFG_ITFM_ENABLE.ubx_key_id, CFG_ITFM_ENABLE},
  // {CFG_ITFM_ANTSETTING.ubx_key_id, CFG_ITFM_ANTSETTING},
  // {CFG_ITFM_ENABLE_AUX.ubx_key_id, CFG_ITFM_ENABLE_AUX},
};

}  // namespace ubx::cfg
