uint8 NOT_AVAILABLE = 0
uint8 CRL = 1            # Communications Research Labratory (CRL),Tokyo, Japan
uint8 NIST = 2           # National Institute of Standards andTechnology (NIST)
uint8 USNO = 3           # U.S. Naval Observatory (USNO)
uint8 BIPM = 4           # International Bureau of Weights andMeasures (BIPM)
uint8 EURO = 5           # European laboratories
uint8 SU = 6             # Former Soviet Union
uint8 NTSC = 7           # National Time Service Center (NTSC) China
uint8 UTC_UNKNOWN = 15   # Unknown time source
uint8 id                 # uc standard id